config/routes.rb
Rails.application.routes.draw do
  resources :subscribers
  resources :posts do
	resources :comments
end
get 'about/index'
get 'promo/index'
get 'posts/index'

get 'promo', to: 'promo#index'
get 'about', to: 'about#index'

root 'promo#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
		validates :name, :presence => true
		validates :title, :presence => true,
											:length => { :minimum => 5 }

		has_many :comments, :dependent => :destroy
    mount_uploader :image, ImageUploader
end

app/models/subscriber.rb
class Subscriber < ApplicationRecord
  validates :email, presence: true
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  http_basic_authenticate_with :name => "admin", :password => "superstrongpassword", :only => :destroy
	def create
		@post = Post.find(params[:post_id])
		@comment = @post.comments.create(params[:comment].permit(:commenter, :body))
		redirect_to post_path(@post)
	end
	def destroy
		@post = Post.find(params[:post_id])
		@comment = @post.comments.find(params[:id])
		@comment.destroy
		redirect_to post_path(@post)
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  http_basic_authenticate_with :name => "admin", :password => "superstrongpassword", :except => [:index, :show]
  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:name, :title, :image, :content)
    end
end

def post_params
params.require(:post).permit(:name, :title, :image, :content)
end

app/controllers/promo_controller.rb
class PromoController < ApplicationController
  def index
  end
end

app/controllers/subscribers_controller.rb
class SubscribersController < ApplicationController
  def index
    @subscribers = Subscriber.all
  end

  def create
    @subscriber = Subscriber.new(subscriber_params)
    # if @subscriber.save
    #   redirect_to about_path, notice: "Ура!"
    # else
    #   redirect_to about_path, notice: "Не ура("
    # end
  end

  private

    def subscriber_params
      params.require(:subscriber).permit(:email)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/promo_helper.rb
module PromoHelper
end

app/helpers/subscribers_helper.rb
module SubscribersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<%= link_to "Blog", posts_path %>

app/views/comments/_comment.html.erb
<p>
	<b>Commenter:</b>
	<%= comment.commenter %>
</p>
<p>
	<b>Comment:</b>
	<%= comment.body %>
</p>
<p>
	<%= link_to 'Destroy Comment', [comment.post, comment],
								:confirm => 'Are you sure?',
								:method => :delete %>
</p>

app/views/comments/_form.html.erb
<%= form_for([@post, @post.comments.build]) do |f| %>
	<div class="field">
		<%= f.label :commenter %><br />
		<%= f.text_field :commenter %>
	</div>
	<div class="field">
		<%= f.label :body %><br />
		<%= f.text_area :body %>
	</div>
		<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AltMedia</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <%= notice %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div>
	<%= form.label :image %>
	<%= form.file_field :image %>
</div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
 <%= form.label :author %>
 <%= form.text_field :author %>
</div>


  <div class="actions">
    <%= form.submit %>
  </div>


<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>


<h6 class="posts">Посты</h6>

<%= link_to 'New Post', new_post_path, class: 'btn_new_post'%>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.name %></td>
        <td><%= post.title %></td>
        <td><%= post.content %></td>
        <td><%= image_tag(post.image.url, alt: 'Image')%></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>



<div class="btn_">
<%= link_to "ALT", promo_path %>
</div>
<div class="btn_">
<%= link_to "О сервисе", about_path %>
</div>



<br>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

<%= image_tag(@post.image.url, class: 'show__img-post', alt: 'Image') if @post.image? %>

<p class="show__name">
  <strong class="show__name-post"></strong>
  <%= @post.name %>
</p>

<p class="show__title">
  <strong class="show__title-post"></strong>
  <%= @post.title %>
</p>

<p class="show__content">
  <strong class="show__content-post"></strong>
  <%= @post.content %>
</p>

app/views/promo/index.html.erb
<div class="header">

  <div class="btn_footer">
      <h4 class="abt"><%= link_to "О проекте", about_path %></h4>
      <h4 class="post"><%= link_to "Посты", posts_path %></h4>
    </div>

  <h8>ALT</h8>
  <h2 class="one"> — ваш помощник </h2>
  <h2 class="two"> в мире устойчивой моды </h2>
  <%= image_tag 'ellipse', class: 'el'%>
  <h3 class="three">*даже маленький шаг может стать частью больших изменений</h3>
</div>

<div class="main">
  <p class="about">Медиа-сервис, который собирает всю <br>информацию про экологичное потребление <br>в моде, и дает возможность <br>осознанно совершать покупки. </p>
  <%= image_tag 'mokup', class: 'mkup'%>
  <%= image_tag 'back', class: 'bg'%>

  <div class="shape s_1">
     <h2 class="phras"> Как обновить старые вещи? </h2>
  </div>

  <div class="shape s_2">
     <h2 class="phras"> Какие материалы выбрать? </h2>
  </div>

  <div class="shape s_3">
     <h2 class="phras"> Экофрендли бренды? </h2>
  </div>

  <div class="shape s_4">
     <h2 class="phras"> Как покупать осознанно? </h2>
  </div>

  <div class="shape s_5">
     <h2 class="phras"> Куда сдать вещи на переработку? </h2>
  </div>
</div>

<h3 class="descrp">Ответы на эти и другие вопросы <br>на нашем медиа-сервисе</h3>
<h4 class="descrp_2">Подпишись на рассылку, чтобы ничего не пропустить</h4>
<%= render "subscribers/form" %>

app/views/subscribers/_form.html.erb
<% @subscriber = Subscriber.new %>
<%= form_for @subscriber do |f| %>
  <%= f.email_field :email, placeholder: "Email" %>
  <%= f.submit "Подписаться"%>
<% end %>

app/views/welcome/index.html.erb
<h1>Hello, Rais!</h1>